### ISSUE TITLE
Separate meta data with data in Catalogues/repositories

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-catalogue-repos#135]
hey,
along Y1 we've often faced some confusion on which data could/should be added to the NSD/VNFD/NSR/VNFR...
I'd like to propose a solution on that, since we're making things more complex, namely by introducing some security validations (md5 on the *Ds, authentication and authorisation).
My proposition is the following: the *D should go 'down' one level, and at the same level of the *D ID, creation date, update date and the md5 (and any other field we think it is necessary). The *D can be validated against the schema, without the remaining (meta-)data interfering with that. Like in

`{id:'...', md5:'...', created_at:'...', updated_at:'...', nsd: {...}}`

What do you think?

**Comment by dang03** [comment]
Completely agree on that, security is on the roadmap as a new feature for Y2. In fact, we have been testing with md5 on son-packages files within Catalogues, and it will be tested on descriptors soon.

**Comment by jbonnet** [comment]
@dang03 I hadn't finished the issue section, sorry... ;-)

**Comment by dang03** [comment]
These changes will be introduced in Catalogues API v2. Related issue #142
