### ISSUE TITLE
Add new field ‘license_type’ to services

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-catalogue-repos#149]

**Comment by dang03** [comment]
1. Where is this field located, in meta-data level or descriptor level?
2. If it is located in meta-data level, when is this field declared, a)once the nsd is stored or b) while the nsd is being stored?
- a) requires a specific put method to update ‘licence_type’ field
- b) requires ‘licence_type’ meta-data passed in the call to store the nsd

**Comment by jbonnet** [comment]
Hi, @dang,
this should be a descriptor field (data level).

**Comment by dang** [comment]
@jbonnet I think you meant @dang03

**Comment by jbonnet** [comment]
Ha, sorry, yes I do, sorry to both...

**Comment by dang03** [comment]
Thank you @jbonnet, then this issue is more related to the son-schema (nsd schema) than catalogues.
