### ISSUE TITLE
Is packages' search by UUID-in-the-URL available? And Services or functions?

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-catalogue-repos#156]
Hi,

Can we search by something like
  `.../packages?uuid=98fd-...`
?
The GK is currently getting `[]` with that query. I know there's the alternative
  `.../packages/98fd-...`

**Comment by dang03** [comment]
Hi @jbonnet,

You can now search descriptors and files this way `.../packages?uuid=98fd-...` only through the Catalogues API v2.
To enable this, Gatekeeper routes to Catalogues must be adopted:
- from `.../catalogues/packages?uuid=98fd-...` to `...catalogues/api/v2/packages?uuid=98fd-...`

This also works for services, functions and files. But we need to be careful, as storing descriptors mixing catalogues API v1 and API v2 will result in having records with and without meta-data in the catalogues, causing `500` errors.
