### ISSUE TITLE
What should happen if the uploaded package metadata is saved but the not file?

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-catalogue-repos#160]
Should the Gatekeeper:
1. undo the metadata save by deleting it?
1. mark the metadata somehow (but in this case the file is completely lost)?

**Comment by dang03** [comment]
My vote would be to have the metadata deleted as it would become inconsistent (the descriptor would have `son_package_uuid` field missing). The GK would have to inform to the uploader about the failure. This would ease future submits and avoid possible 409 Conflict errors.

**Comment by jbonnet** [comment]
Ok, sound reasonable…
But packages have several versions, with services, functions and specific managers. Should they all be deleted? But they can be reused, for example, a second version of a package only changes one of the functions, but not the service: when the old version of the package is to be deleted, only the old version of the function that was updated should be deleted..

Am I mixing up things?!?

**Comment by dang03** [comment]
The items to be deleted if the package POST fails should be the new items that the package included (to restore state before the failure).
In the process to store a new service, function, package... from the GK to the Catalogue, if a new item is stored, the response code is a 201. If the item already existed in the Catalogue, the response is 200. 
The GK can delete those items which response was 201 (new ones) and keep the ones that already were there.
When an old version of a package is to be deleted, only services and functions of the old version should be deleted (only if they are not a dependency for another package).
