### ISSUE TITLE
Update meta-data for son-package API

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-catalogue-repos#161]
For a son-package file POST, add new meta-data based on `vendor`, `name` and `version`:
- This meta-data will be included in form of custom header

`att = request.env['HTTP_CONTENT_DISPOSITION']`
`vendor = request.env['HTTP_VENDOR']`
`name = request.env['HTTP_NAME']`
`version = request.env['HTTP_VERSION']`

**Comment by dang03** [comment]
To extend the API in-line with SON-Imagestore:
- POST/GET/PUT/DELETE /son-packages/uuid
For a son-package file POST, add new meta-data based on `vendor`, `name` and `version` :
- POST/GET/PUT/DELETE /son-packages/vendor/name/version

Others methods:
- GET /son-packages/uuid
- GET /son-packages/vendor/name/version
- GET /healthcheck
- GET /config

**Comment by jbonnet** [comment]
@dang03

Are you planning to push files from the Catalogues to the Image Store? Wouldn’t it be better to do it directly from the GK?

**Comment by dang03** [comment]
@jbonnet 
No, the idea of this is to have an API similar to the one presented for the SON-Imagestore. Remember that we discussed on how to add vendor, name, version meta-data to package files ( issue #157 ), this is in order to support both custom headers and  '/son-packages/vendor/name/version' queries.

For Healthcheck and config endpoints, we could see if they are important/required to be also implemented in the Catalogues.

**Comment by dang03** [comment]
The Gatekeeper/son-gtkpkg and the Catalogue are successfully storing son-packages file with the new added metadata, e.g.:
`{
    "_id" : "c3295743-0fb7-4f9d-8956-31f0c672afa9",
    "grid_fs_id" : "58e4b23b7dc5890001000002",
    "grid_fs_name" : "sonata-demo.son",
    "md5" : "9c8a66d5caa756bbb5d2ed4c56e27214",
    "updated_at" : ISODate("2017-04-05T09:00:43.872Z"),
    "created_at" : ISODate("2017-04-05T09:00:43.699Z"),
    "vendor" : "eu.sonata-nfv.package",
    "name" : "sonata-demo",
    "version" : "0.3"
}`
