### ISSUE TITLE
Docker compose fails

### ISSUE THREAD

**Issue by olivierto** [sonata-nfv/son-catalogue-repos#183]
Hello there! 
I'm trying to use the catalogue repos with the docker-compose file. 
But this leads me to an error with the docker registry ... (which seems to be off for now)
Is this normal? 

    Pulling son-catalogue-repos-doc (registry.sonata-nfv.eu:5000/son-catalogue-repos:latest)...
    ERROR: Get https://registry.sonata-nfv.eu:5000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by dang03** [comment]
Hello,
The problem is that the docker_compose is trying to get the docker image from the registry.sonata-nfv.eu, which is the internal project repository. In order to solve this, we are going to update the docker_compose files so it can get the last “stable version” of the container correctly.

We will update this issue as soon as the files are updated. Thank you for writing us.

**Comment by olivierto** [comment]
Thanks for your answer. I'll wait till you fix it  👍

**Comment by dang03** [comment]
Hello,
The docker-compose files have been updated. We have tested the docker-compose.yml and works fine now (docker-compose_test.yml won't work outside the project). If you find any further problems, please contact us. Thank you and best regards.

**Comment by olivierto** [comment]
Hello, thanks for your reactivity! i just tried the setup. Docker compose instantiate the containers properly but MongoExpress output some errors.
`mongoexpress_1       | Welcome to mongo-express
mongoexpress_1       | ------------------------
mongoexpress_1       |
mongoexpress_1       |
mongoexpress_1       | Mongo Express server listening at http://0.0.0.0:8081
mongoexpress_1       | Server is open to allow connections from anyone (0.0.0.0)
mongoexpress_1       | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
mongoexpress_1       |
mongoexpress_1       | /node_modules/mongodb/lib/server.js:265
mongoexpress_1       |         process.nextTick(function() { throw err; })
mongoexpress_1       |                                       ^
mongoexpress_1       | MongoError: failed to connect to server [mongo:27017] on first connect
mongoexpress_1       |     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
mongoexpress_1       |     at emitOne (events.js:96:13)
mongoexpress_1       |     at Pool.emit (events.js:188:7)
mongoexpress_1       |     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
mongoexpress_1       |     at Connection.g (events.js:291:16)
mongoexpress_1       |     at emitTwo (events.js:106:13)
mongoexpress_1       |     at Connection.emit (events.js:191:7)
mongoexpress_1       |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
mongoexpress_1       |     at Socket.g (events.js:291:16)
mongoexpress_1       |     at emitOne (events.js:96:13)
mongoexpress_1       | Welcome to mongo-express
mongoexpress_1       | ------------------------`


Any way i diasbled mongoexpress in the compose file :)
